# Welcome to Numpy Introduction Notebook

In [4]:
import numpy as np

## DataTypes & Attributes

In [3]:
# Numpy's main dataype is ndarray
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.7]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [12]:
a1.ndim, a2.ndim

(1, 2)

## 2. Creating Arrays

In [10]:
sample_array = np.array([1,2,3])

In [13]:
sample_array

array([1, 2, 3])

In [14]:
ones = np.ones(5)

In [15]:
ones

array([1., 1., 1., 1., 1.])

In [18]:
zeros = np.zeros((2,3))

In [19]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0,10,2)

In [21]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0,10, size=(3,5))

In [24]:
random_array

array([[1, 1, 9, 2, 7],
       [4, 0, 9, 0, 2],
       [7, 6, 2, 5, 4]])

In [25]:
random_array.size

15

## Aggregation
Aggregation = performing the same operation on a number of things

In [1]:
listy_list = [1,2,3]
type(listy_list)

list

In [2]:
sum(listy_list)

6

In [5]:
a1 = np.array([1,2,3])

In [6]:
np.sum(a1)

6

In [8]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [9]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

6.76 ms ± 260 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
40.3 µs ± 2.81 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
